### PR TITLE
Add Point feature

### PR DESCRIPTION
**Pull request by ocefpaf**
@kwilcox Note that I just modified the GeoJSON because that is all I need. Do you want me to modify the Shapefile as well?

PS: I am curious why are you adding the HF-Radars stations as Polygons instead of Points in the shapefile?

https://github.com/SECOORA/static_assets/blob/master/hfradar/convert.py#L190

@vembus: Once this modification is merged I will send another PR with the notebook that will glue all this together and create the map.

### CODE REVIEW

**Comment by kwilcox** [comment]
Shapefiles should only have one type of geometry in them,  so I chose polygon to cover the wedges.

I'm off for a few days, go ahead and merge.

**Comment by ocefpaf** [comment]
> Shapefiles should only have one type of geometry in them, so I chose polygon to cover the wedges.

OK.  I went for two [files](https://github.com/ocefpaf/secoora_assets_map/blob/gh-pages/test_shapefile.ipynb), but I guess that one file is better.

> I'm off for a few days, go ahead and merge.

I cannot.  No rights...

**Comment by kwilcox** [comment]
@ocefpaf should have rights now

**Comment by ocefpaf** [comment]
Just got the email.  Thanks!

**Pull request merged**
